
/* eslint-disable */
/**
 * Generated API definitions.
 */
import { anyApi } from "convex/server";

/**
 * A type-safe API interface for the Convex functions.
 * In a standard environment, this is generated by the Convex CLI.
 */
export const api: any = anyApi;
